kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team2-argocd-create-namespaces
subjects:
  - kind: ServiceAccount
    name: team2-argocd-application-controller
    namespace: team2-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-namespaces
