kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd-developers
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app1-developers
  source:
    path: overlays/app1
    repoURL: https://github.com/tcynic/argotest.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true